CREATE DATABASE [BDTeste]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDTeste', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDTeste.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDTeste_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDTeste_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BDTeste] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [BDTeste] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BDTeste] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BDTeste] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BDTeste] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BDTeste] SET ARITHABORT OFF 
GO
ALTER DATABASE [BDTeste] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BDTeste] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BDTeste] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [BDTeste] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BDTeste] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BDTeste] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BDTeste] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BDTeste] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BDTeste] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BDTeste] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BDTeste] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BDTeste] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BDTeste] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BDTeste] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BDTeste] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BDTeste] SET  READ_WRITE 
GO
ALTER DATABASE [BDTeste] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BDTeste] SET  MULTI_USER 
GO
ALTER DATABASE [BDTeste] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BDTeste] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BDTeste] SET DELAYED_DURABILITY = DISABLED 
GO
USE [BDTeste]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [BDTeste]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [BDTeste] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
